name: cron

on:
  push:
    paths:
      - ".github/workflows/cron.yml"
  schedule:
    - cron: "0 18 * * 5" # friday 18:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  build-gpapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo build --manifest-path gpapi/Cargo.toml --release
      - uses: actions/upload-artifact@v6
        with:
          name: gpapi
          path: ./gpapi/target/release/gpapi

  Signal-Android:
    env:
      PACKAGE: org.thoughtcrime.securesms
      TYPE: playstore
    needs: build-gpapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: gpapi
          path: /usr/local/bin/
      - run: |
          sudo chmod +x /usr/local/bin/gpapi
          VERSION=$(gpapi --email "${{ secrets.EMAIL }}" --aas-token "${{ secrets.AAS_TOKEN }}" --package "${{ env.PACKAGE }}")
          if ! grep -F " v${VERSION} " "history/${{ github.job }}.md" >/dev/null; then
            echo "MESSAGE=âš ï¸  ${{ github.job }} v${VERSION} ${{ env.TYPE }} not already checked" >> $GITHUB_ENV
            sed -i "s/^  VERSION:.*/  VERSION=${VERSION}/g" ".github/workflows/${{ github.job }}.yml"
            sed -i "6a | v${VERSION}  | 2026-??-??   | ðŸŸ¡ In progress| - |" "history/${{ github.job }}.md"
            echo "CREATE_PR=1" >> $GITHUB_ENV
          else
            echo "MESSAGE=âœ… ${{ github.job }} v${VERSION} already checked" >> $GITHUB_ENV
          fi
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@cron
        if: ${{ env.MESSAGE }}
        with:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          mode: "cron"
          MESSAGE: ${{ env.MESSAGE}}
      - if: ${{ env.CREATE_PR }}
        run: |
          PR_EXISTS=$(gh pr list --state open --search "title:\"ci: check ${{ github.job }} v${{ env.VERSION }}\"" --json number -q 'length')
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v8
        if: env.PR_EXISTS == '0'
        with:
          token: ${{ secrets.PAT_CRON }}
          commit-message: "ci: check ${{ github.job }} v${{ env.VERSION }} ${{ env.TYPE }}"
          title: "ci: check ${{ github.job }} v${{ env.VERSION }} ${{ env.TYPE }}"
          body: "Check ${{ github.job }} v${{ env.VERSION }} ${{ env.TYPE }}"
          branch: check-${{ github.job }}-v${{ env.VERSION }}-${{ env.TYPE }}
