name: cron

on:
  push:
    paths:
      - ".github/workflows/cron.yml"

jobs:
  build-gpapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo build --manifest-path gpapi/Cargo.toml --release
      - uses: actions/upload-artifact@v6
        with:
          name: gpapi
          path: ./gpapi/target/release/gpapi

  Signal-Android-playstore:
    needs: build-gpapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: gpapi
          path: /usr/local/bin/
      - run: |
          sudo chmod +x /usr/local/bin/gpapi
          ls -Rlsah /usr/local/bin/gpapi
          VERSION=$(gpapi --email "${{ secrets.EMAIL }}" --aas-token "${{ secrets.AAS_TOKEN }}" --package "org.thoughtcrime.securesms")
          if ! grep -F " v${VERSION} " "history/${{ github.job }}.md" >/dev/null; then
            echo "MESSAGE=⚠️  ${{ github.job }} v${VERSION} not already checked" >> $GITHUB_ENV
          else
            echo "MESSAGE=✅  ${{ github.job }} v${VERSION} already checked" >> $GITHUB_ENV
          fi
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        if: ${{ env.MESSAGE }}
        with:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          mode: "cron"
          MESSAGE: ${{ env.MESSAGE}}
