name: cron

on:
  push:
    paths:
      - ".github/workflows/cron.yml"

jobs:
  build-gpapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo build --manifest-path gpapi/Cargo.toml --release
      - uses: actions/upload-artifact@v6
        with:
          name: gpapi
          path: ./gpapi/target/release/gpapi

  Signal-Android-playstore:
    needs: build-gpapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: gpapi
          path: .local/bin/gpapi
      - run: |
          chmod +x .local/bin/gpapi
          VERSION=$(gpapi --email "${{secrets.EMAIL}}" --aas-token "${{secrets.AAS_TOKEN}}" --package "org.thoughtcrime.securesms")
          if ! grep -F " v${VERSION} " history/Signal-Android.md >/dev/null; then
            echo "⚠️  ${VERSION} not already checked"
          else
            echo "✅ ${VERSION} already checked"
          fi
