name: cron

on:
  push:
    paths:
      - ".github/workflows/cron.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cargo new bibin
          cd bibin
          cargo run
