name: Molly-Android

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

env:
  SIGNATURE_SHA256: 6aa80fdf4a8cc13737cfb434fc0cde486f09cf8fcda21a67bea5ee1ca2700886

jobs:
  molly-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Official
        run: |
          wget https://github.com/mollyim/mollyim-android/releases/download/v${{ inputs.VERSION }}/Molly-v${{ inputs.VERSION }}.apk
          /usr/local/lib/android/sdk/build-tools/36.1.0/apksigner verify -v --print-certs --min-sdk-version 24 Molly-v${{ inputs.VERSION }}.apk | grep $SIGNATURE_SHA256
      - name: Build
        run: |
          git clone https://github.com/mollyim/mollyim-android.git -b v${{ inputs.VERSION }} --depth 1
          cd mollyim-android/reproducible-builds
          docker build -t reproducible-molly -f ../Dockerfile ..
          docker run --rm -v ./certs:/molly/app/certs:ro -v ./outputs:/molly/app/build/outputs reproducible-molly:latest :app:assembleProdWebsiteRelease || docker run --rm -v ./certs:/molly/app/certs:ro -v ./outputs:/molly/app/build/outputs reproducible-molly:latest :app:assembleProdGmsWebsiteRelease
      - name: Molly apkdiff
        run: |
          python mollyim-android/reproducible-builds/apkdiff/apkdiff.py Molly-v${{ inputs.VERSION }}.apk mollyim-android/reproducible-builds/outputs/apk/prodWebsite/release/Molly-unsigned-v${{ inputs.VERSION }}.apk
      - name: Signal apkdiff
        run: |
          git clone --depth 1 https://github.com/signalapp/Signal-Android
          pip install uv
          cd Signal-Android/reproducible-builds/apkdiff
          uv sync
          sed -i '/IGNORE_FILES = \[/a "META-INF/KEY0.RSA",' apkdiff.py
          sed -i '/IGNORE_FILES = \[/a "META-INF/KEY0.SF",' apkdiff.py
          uv run apkdiff.py ../../../Molly-v${{ inputs.VERSION }}.apk ../../../mollyim-android/reproducible-builds/outputs/apk/prodWebsite/release/Molly-unsigned-v${{ inputs.VERSION }}.apk

  libsignal-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Get libsignal version
        run: |
          LIBSIGNAL_VERSION=$(curl -s "https://raw.githubusercontent.com/mollyim/mollyim-android/refs/tags/v${{ inputs.VERSION }}/gradle/libs.versions.toml" | grep "libsignal-client = \"[0-9\.-]*\"" | cut -d= -f2 | xargs)
          echo "LIBSIGNAL_VERSION=$LIBSIGNAL_VERSION" >> $GITHUB_ENV
          echo "LIBSIGNAL_VERSION_MAJOR=$(echo $LIBSIGNAL_VERSION | cut -d- -f1)" >> $GITHUB_ENV
      - name: Download libsignal from maven
        run: |
          wget https://dl.cloudsmith.io/public/mollyim/libsignal/maven/im/molly/libsignal-android/${{ env.LIBSIGNAL_VERSION }}/libsignal-android-${{ env.LIBSIGNAL_VERSION }}.aar
          wget https://dl.cloudsmith.io/public/mollyim/libsignal/maven/im/molly/libsignal-client/${{ env.LIBSIGNAL_VERSION }}/libsignal-client-${{ env.LIBSIGNAL_VERSION }}.jar
      - name: Free up disk space
        uses: BarbossHack/reproducible/.github/actions/free-up-github-action@master
      - name: Build
        run: |
          git clone https://github.com/mollyim/libsignal -b v${{ env.LIBSIGNAL_VERSION }} --depth 1
          cd libsignal
          docker build -f Dockerfile.java -t libsignal-builder .
          docker run --memory=12g --rm -v $(pwd):/libsignal --entrypoint="" libsignal-builder:latest ./java/gradlew -p java --no-daemon --max-workers=1 -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m" -Dkotlin.incremental=true -Dkotlin.compiler.execution.strategy=in-process build
      - name: Find
        run: |
          find . -name "*.aar"
          find . -name "*.jar"
      - name: Hashes
        run: |
          echo "libsignal-android"
          sha256sum ./libsignal/java/android/build/outputs/aar/libsignal-android-release.aar ./libsignal-android-${{ env.LIBSIGNAL_VERSION }}.aar
          echo "libsignal-client"
          sha256sum ./libsignal/java/client/build/libs/libsignal-client-${{ env.LIBSIGNAL_VERSION_MAJOR }}.jar ./libsignal-client-${{ env.LIBSIGNAL_VERSION }}.jar
      - name: Diffoscope libsignal-android
        run: docker run --rm -w $(pwd) -v $(pwd):$(pwd) registry.salsa.debian.org/reproducible-builds/diffoscope --no-progress --exclude-command objdump --exclude-command readelf --exclude-command strings --exclude-command zipdetails --exclude-command xxd ./libsignal/java/android/build/outputs/aar/libsignal-android-release.aar ./libsignal-android-${{ env.LIBSIGNAL_VERSION }}.aar
      - name: Diffoscope libsignal-client
        run: |
          docker run --rm -w $(pwd) -v $(pwd):$(pwd) registry.salsa.debian.org/reproducible-builds/diffoscope --no-progress --exclude-command objdump --exclude-command readelf --exclude-command strings --exclude-command zipdetails --exclude-command xxd ./libsignal/java/client/build/libs/libsignal-client-${{ env.LIBSIGNAL_VERSION_MAJOR }}.jar ./libsignal-client-${{ env.LIBSIGNAL_VERSION }}.jar

  notify:
    needs: [molly-verify, libsignal-verify]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          VERSION: ${{ inputs.VERSION }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
