name: Signal-Android

on:
  push:
    paths:
      - ".github/workflows/Signal-Android.yml"

env:
  VERSION: 7.69.2
  SIGNATURE_SHA256: 4be4f6cd5be844083e900279dc822af65a547fecc26aba7ff1f5203a45518cd8

jobs:
  website-official:
    runs-on: ubuntu-latest
    steps:
      - name: Official
        run: |
          wget https://updates.signal.org/android/Signal-Android-website-prod-universal-release-${{ env.VERSION }}.apk

          /usr/local/lib/android/sdk/build-tools/36.1.0/apksigner verify -v --print-certs --min-sdk-version 24 Signal-Android-website-prod-universal-release-${{ env.VERSION }}.apk | grep $SIGNATURE_SHA256
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: website-official
          path: Signal-Android-website-prod-universal-release-${{ env.VERSION }}.apk

  playstore-official:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          cargo build --manifest-path gpapi/Cargo.toml --release
          ./gpapi/target/release/gpapi --email "${{ secrets.EMAIL }}" --aas-token "${{ secrets.AAS_TOKEN }}" --package "${{ env.PACKAGE }}" --output=./playstore-official/
          PLAYSTORE_VERSION=$(cat ./playstore-official/VERSION)

          /usr/local/lib/android/sdk/build-tools/36.1.0/apksigner verify -v --print-certs --min-sdk-version 24 ./playstore-official/org.thoughtcrime.securesms/org.thoughtcrime.securesms.apk | grep $SIGNATURE_SHA256

          if [[ "$VERSION" == "$PLAYSTORE_VERSION" ]]; then
            echo "✅ Versions match"
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Versions differ: expected $VERSION but got $PLAYSTORE_VERSION"
            echo "valid=false" >> $GITHUB_OUTPUT
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: playstore-official
          path: ./playstore-official/

  website-build:
    needs: [website-official]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: website-official
      - name: Build
        run: |
          git clone https://github.com/signalapp/Signal-Android -b v${{ env.VERSION }} --depth 1
          cd Signal-Android/reproducible-builds
          docker build -t signal-android .
          cd ..
          function build_sa() { docker run --memory=6g --rm -v "$(pwd)":/project -w /project --user "$(id -u):$(id -g)" signal-android ./gradlew --warning-mode=all --no-daemon --max-workers=1 --stacktrace -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m" -Dkotlin.daemon.jvmargs="-Xmx256m -XX:MaxMetaspaceSize=512m" -Dkotlin.incremental=true -Dkotlin.compiler.execution.strategy=in-process assembleWebsiteProdRelease; }
          build_sa || build_sa
      - name: Apkdiff
        run: |
          pip install uv
          cd Signal-Android/reproducible-builds/apkdiff
          uv sync
          uv run apkdiff.py ../../../Signal-Android-website-prod-universal-release-${{ env.VERSION }}.apk ../../../Signal-Android/app/build/outputs/apk/websiteProd/release/Signal-Android-website-prod-universal-release-unsigned-${{ env.VERSION }}.apk

  playstore-build:
    needs: [playstore-official]
    if: needs.playstore-official.outputs.valid == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: playstore-official
      - name: Build
        run: |
          git clone https://github.com/signalapp/Signal-Android -b v${{ env.VERSION }} --depth 1
          cd Signal-Android/reproducible-builds
          docker build -t signal-android .
          cd ..

          function build_sa() { docker run --memory=6g --rm -v "$(pwd)":/project -w /project --user "$(id -u):$(id -g)" signal-android ./gradlew --warning-mode=all --no-daemon --max-workers=1 --stacktrace -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m" -Dkotlin.daemon.jvmargs="-Xmx256m -XX:MaxMetaspaceSize=512m" -Dkotlin.incremental=true -Dkotlin.compiler.execution.strategy=in-process bundlePlayProdRelease; }
          build_sa || build_sa

          which bundletool || true
          curl -L https://github.com/google/bundletool/releases/download/1.18.3/bundletool-all-1.18.3.jar -o bundletool.jar
          java -jar bundletool.jar build-apks --bundle=./app/build/outputs/bundle/playProdRelease/Signal-Android-play-prod-release.aab --output-format=DIRECTORY --output=apks
          tree -h apks
      - name: Apkdiff
        run: |
          pip install uv
          cd Signal-Android/reproducible-builds/apkdiff
          uv sync

          uv run apkdiff.py ../../../playstore-official/org.thoughtcrime.securesms/org.thoughtcrime.securesms.apk ../../apks/splits/base-master.apk

          uv run apkdiff.py ../../../playstore-official/org.thoughtcrime.securesms/org.thoughtcrime.securesms.config.arm64_v8a.apk ../../apks/splits/base-arm64_v8a.apk

          uv run apkdiff.py ../../../playstore-official/org.thoughtcrime.securesms/org.thoughtcrime.securesms.config.xxhdpi.apk ../../apks/splits/base-xxhdpi.apk

  libsignal:
    needs: [website-official]
    runs-on: ubuntu-latest
    steps:
      - name: Get libsignal version
        run: |
          LIBSIGNAL_VERSION=$(curl -s "https://raw.githubusercontent.com/signalapp/Signal-Android/refs/tags/v${{ env.VERSION }}/gradle/libs.versions.toml" | grep "libsignal-client = \"[0-9\.]*\"" | cut -d= -f2 | xargs)
          echo "LIBSIGNAL_VERSION=$LIBSIGNAL_VERSION" >> $GITHUB_ENV
      - name: Official
        run: |
          wget https://build-artifacts.signal.org/libraries/maven/org/signal/libsignal-android/${{ env.LIBSIGNAL_VERSION }}/libsignal-android-${{ env.LIBSIGNAL_VERSION }}.aar
          wget https://build-artifacts.signal.org/libraries/maven/org/signal/libsignal-client/${{ env.LIBSIGNAL_VERSION }}/libsignal-client-${{ env.LIBSIGNAL_VERSION }}.jar
      - name: Free up disk space
        uses: BarbossHack/reproducible/.github/actions/free-up-github-action@master
      - name: Build
        run: |
          git clone https://github.com/signalapp/libsignal -b v${{ env.LIBSIGNAL_VERSION }} --depth 1
          pushd libsignal/java
          make || make
          popd
          find . -name "*.jar"
      - name: Hashes
        run: |
          echo "libsignal-android"
          sha256sum ./libsignal/java/android/build/outputs/aar/libsignal-android-release.aar ./libsignal-android-${{ env.LIBSIGNAL_VERSION }}.aar
          echo "libsignal-client"
          sha256sum ./libsignal/java/client/build/libs/libsignal-client-${{ env.LIBSIGNAL_VERSION }}.jar ./libsignal-client-${{ env.LIBSIGNAL_VERSION }}.jar
      - name: Diffoscope libsignal-android
        run: docker run --rm -w $(pwd) -v $(pwd):$(pwd) registry.salsa.debian.org/reproducible-builds/diffoscope --no-progress --exclude-command objdump --exclude-command readelf --exclude-command strings --exclude-command zipdetails --exclude-command xxd ./libsignal/java/android/build/outputs/aar/libsignal-android-release.aar ./libsignal-android-${{ env.LIBSIGNAL_VERSION }}.aar
      - name: Diffoscope libsignal-client
        run: |
          zip -d ./libsignal-client-${{ env.LIBSIGNAL_VERSION }}.jar '*.dylib' '*.dll'
          docker run --rm -w $(pwd) -v $(pwd):$(pwd) registry.salsa.debian.org/reproducible-builds/diffoscope --no-progress --exclude-command objdump --exclude-command readelf --exclude-command strings --exclude-command zipdetails --exclude-command xxd ./libsignal/java/client/build/libs/libsignal-client-${{ env.LIBSIGNAL_VERSION }}.jar ./libsignal-client-${{ env.LIBSIGNAL_VERSION }}.jar

  notify:
    needs: [libsignal, website-build, playstore-build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
